// <auto-generated />
namespace Calisma.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class table_names_edited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_names_edited));
        
        string IMigrationMetadata.Id
        {
            get { return "201807140703363_table_names_edited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
